### ISSUE TITLE
0.5.0 There is an uncommitted error in the seata-server root.data file, causing an infinite number of retries

### ISSUE THREAD

**Issue by lynk-coder** [seata/seata#881]
![96FB4356-8EA9-4457-8A94-4FA16C24697F](https://user-images.githubusercontent.com/23651124/56580055-47ae0500-6604-11e9-869f-dbb76b3ba36f.png)

The above is the relevant content of infinite retry printing.
The content is repeated.

**Comment by HouZhiHouJue** [comment]
This bug does exist. When the client transaction is not committed, if the connection with the server is disconnected (crash or network problem), the server will initiate an infinite retry. When the client reconnects, the server will be based on the Look for the app:ip:port connection->app:ip connection->app connection to keep trying again. It seems that there is no problem, but since the client RM is not registered immediately at startup, and the client does not maintain a long connection for RM at all, the server will fall into the wireless loop.

**Comment by lynk-coder** [comment]
Yes, the premise of this reconnection mechanism is to ensure that the service reconnects RM without restarting, otherwise the KEY of corresponding service will also change after the service restarts, leading to the problem of infinite retry.

**Comment by CoffeeLatte007** [comment]
it will fix in next version

**Comment by lynk-coder** [comment]
The team worked hard. thank you.

**Comment by lynk-coder** [comment]
Resolved, I initialize the dynamic switch log level code after the Config configuration can be.

**Comment by HouZhiHouJue** [comment]
> Resolved, I initialize the dynamic switch log level code after the Config configuration can be.

You have not solved the problem of transaction retry compensation.

**Comment by lynk-coder** [comment]
Hahaha ! 
I sent it to the wrong place

**Comment by dreamoftch** [comment]
hi @HouZhiHouJue @CoffeeLatte007   i am wondering why they define the `app:ip:port` as the clientId for the rm connection, since the `rm port` retrieved by tc will always changed after rm restarted, confusing...

**Comment by HouZhiHouJue** [comment]
There is nothing wrong with their lookup logic. You don't fully understand it. I suggest you look at the code for ChannelManager.java#getChannel.

**Comment by xingfudeshi** [comment]
fix #830 will be release on 0.6.0
